### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by nigelhorne** [whosonfirst-data/whosonfirst-data-venue#5]
Is this venue project dead?  The venue data can't be downloaded (403 error) and the geocode.earth system you're told to use doesn't include the venue data.  The blog on the site hasn't been updated since 2019.  It'll be sad to lose it, I used it to verify places on my Family Tree.

**Comment by stepps00** [comment]
Hey @nigelhorne - the venue data is not actively curated or regularly updated, but Who's On First still maintains the venue data in per-country repositories (per-region, in the case of the US). Examples:

- New York (US) venues: https://github.com/whosonfirst-data/whosonfirst-data-venue-us-ny
- Mexico: https://github.com/whosonfirst-data/whosonfirst-data-venue-mx

You should also be able to browse venue records (along with the rest of Who's On First) in the [Spelunker](https://spelunker.whosonfirst.org/), though the hosted bundles and distribution files are no longer available from the Who's On First site.

If you'd like to create your own distribution file, you can take a look at these docs about how to do so:

- https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/how_to/building_a_combined_distribution.md
-https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/how_to/building_a_single_repo_distribution.md

**Comment by nigelhorne** [comment]
Thanks for the reply.  It’s actually the venue data I think I need since that has places like churches that are useful for genealogy.  I’m going to attempt to create my own database from the geojson files.  Once that’s done the code will appear in Geo::Coder::Free.

**Comment by thisisaaronland** [comment]
As an old-skool Perl programmer it makes me happy to know WOF is holding hands with Perl!

**Comment by nigelhorne** [comment]
Closing.
